  version: '3.8'
  services:
    db:
      image: postgres
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123
        - POSTGRES_DB=shopdb

    api1: &api
      build: .
      ports:
        - 8080:8080
      environment:
        - DB_HOST=db
      depends_on:
        - db

    api2: 
      <<: *api
      ports:
        - 8081:8080

    nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - api1
        - api2
      ports:
        - "9999:9999"
        