version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=shopdb

  api1: &api
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db